# git log format
# used to show to user so they can review prior to pushing changes to origin
git_log_format: --pretty=format:"%h%x09%an%x09%ad%x09%s" --graph
git_log_number_of_lines: 10

# base path where all the respective git repos are housed.  Only
# one value supported.
# ex: 'git@github.com:octocat'
git_repo_base_clone_path:

# The user of the script can choose to update all repos or
# a subset of that.  This is the canonical complete list of
#  i.e.
# KNOWN_REPOS = [
#   {
#     'name'  : 'project-x',
#     'branch': 'development',
#   },
#   ...
# ]
known_repos:
    - name:          RepoName1
      branch:        development
      submodule_dir: src/vendor

    - name:          RepoName2
      branch:        master
      submodule_dir: src/vendor

# For each repo (listed via KNOWN_REPOS, this is the 
# name (git repo name) of
# the submodule to be updated.
target_submodule_name:

# this is the branch name that target submodule
# will be pulled to the HEAD of
target_submodule_target_branch:

# where to send the output from report.rb
# if empty, will not attempt to send email
report_email: example@example.com