# base path where all the respective git repos are housed.  Only
# one value supported.
# ex: 'git@github.com:octocat'
git_repo_base_clone_path:
# The user of the script can choose to update all repos or
# a subset of that.  This is the canonical complete list of
#  i.e.
# KNOWN_REPOS = [
#   {
#     'name'  : 'project-x',
#     'branch': 'development',
#   },
#   ...
# ]
known_repos:
    - name:          RepoName1
      branch:        development
      submodule_dir: src/vendor

    - name:          RepoName2
      branch:        master
      submodule_dir: src/vendor

# For each repo (listed via KNOWN_REPOS, this is the 
# name (git repo name) of
# the submodule to be updated.
target_submodule_name:

# the relative path (in contexts of the top dir of
# a repo using the submodule)
# to the target sub-module
target_submodule_relative_path:

# this is the branch name that target submodule
# will be pulled to the HEAD of
target_submodule_target_branch: